use [CRONUS] 
Select * from [NAV App]
SELECT * from [NAV App Dependencies]
SELECT * from [NAV App Object Prerequisites]
Select * from [NAV App Capabilities]
Select * from [NAV App Object Metadata]
Select * from [NAV App Tenant App]
Select * from [NAV App Data Archive]
Select * from [NAV App Installed App]